#!/usr/bin/bash

# 'usage: binary 
#	<path workload file> 
#	<path result file> 
#	<runtime benchmark (min)> 
#	<#threads> 
#	<throughput (ops/sec)/-> 
#	<eventFile> 
#	[<list remote ycsb nodes>]'

python3 /root/YCSB/front_end/availability/runMongoDBAvai.py workloads/workload results/result 20 50 600 events/mongodb/stopStartEvent
