#!/bin/bash

ipsInCluster="172.17.8.106,172.17.8.107,172.17.8.105,172.17.8.108"	# Comma separated list of IPs in cluster (first one is access node)
runtimeBenchmark=15 					# In minutes
outputFile="results/result" 				# output file 
readPreference="secondary"				# read preference (nearest, primary, primarypreferred, secondary, secondarypreferred)
writeConcern="journal"					# write concern (safe, journal, normal, fsync_safe, replicas_safe, majority) 
seedForOperationSelection=159874549 			# seed for operation selection random generator 
writePeriod=500 					# write a new timestamp with this period (milliseconds)
accuracy=250						# accuracy in microseconds 
timeout=1000 						# timeout in microseconds
lastSamplepoint=10000 					# no read samplepoints this amount of microseconds after writer operation 
amountOfSideLoadThreads=120 				# amount of YCSB sideload client threads
requestedThroughputSideLoadThreads=200 			# throughput (operation/sec) requested by sideload client threads

python3 front_end/consistency/runMongodbConsistency.py $ipsInCluster $runtimeBenchmark $outputFile $readPreference $writeConcern $seedForOperationSelection $writePeriod $accuracy $timeout $lastSamplepoint -1 False $amountOfSideLoadThreads $requestedThroughputSideLoadThreads
